"""empty message

Revision ID: 95f573fea691
Revises: 
Create Date: 2018-06-02 17:50:22.842205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f573fea691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('orders', sa.Column('orderdesc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'orderdesc')
    op.add_column('goods', sa.Column('is_you', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_constraint(None, 'goodguiges', type_='foreignkey')
    # ### end Alembic commands ###
